import type { Lead, Campaign } from './types';

export const leads: Lead[] = [
  {
    id: '1',
    name: 'Alice Johnson',
    email: 'alice.j@example.com',
    avatar: 'https://picsum.photos/id/1011/100/100',
    status: 'Contacted',
    campaign: 'Summer Sale 2024',
    source: 'Website Form',
    lastContacted: '2024-07-28',
    history: [
      { date: '2024-07-28', action: 'Emailed', details: 'Sent introductory email.' },
      { date: '2024-07-25', action: 'Created', details: 'Lead created from website form.' },
    ],
  },
  {
    id: '2',
    name: 'Bob Williams',
    email: 'bob.w@example.com',
    avatar: 'https://picsum.photos/id/1012/100/100',
    status: 'Converted',
    campaign: 'Q3 Webinar',
    source: 'LinkedIn',
    lastContacted: '2024-07-27',
    history: [
      { date: '2024-07-27', action: 'Converted', details: 'Signed up for Premium Plan.' },
      { date: '2024-07-26', action: 'Call', details: 'Demo call with sales team.' },
      { date: '2024-07-24', action: 'Emailed', details: 'Replied to follow-up email.' },
    ],
  },
  {
    id: '3',
    name: 'Charlie Brown',
    email: 'charlie.b@example.com',
    avatar: 'https://picsum.photos/id/1013/100/100',
    status: 'Pending',
    campaign: 'Newsletter Signup',
    source: 'Organic Search',
    lastContacted: '2024-07-29',
    history: [
        { date: '2024-07-29', action: 'Created', details: 'New lead from newsletter signup.' },
    ],
  },
  {
    id: '4',
    name: 'Diana Miller',
    email: 'diana.m@example.com',
    avatar: 'https://picsum.photos/id/1014/100/100',
    status: 'Responded',
    campaign: 'Summer Sale 2024',
    source: 'Facebook Ads',
    lastContacted: '2024-07-29',
    history: [
        { date: '2024-07-29', action: 'Emailed', details: 'Responded with questions about pricing.' },
        { date: '2024-07-28', action: 'Emailed', details: 'Sent initial outreach.' },
    ],
  },
  {
    id: '5',
    name: 'Ethan Davis',
    email: 'ethan.d@example.com',
    avatar: 'https://picsum.photos/id/1015/100/100',
    status: 'Pending',
    campaign: 'Q3 Webinar',
    source: 'Referral',
    lastContacted: '2024-07-30',
    history: [
        { date: '2024-07-30', action: 'Created', details: 'Referred by an existing customer.' },
    ],
  },
  {
    id: '6',
    name: 'Fiona Garcia',
    email: 'fiona.g@example.com',
    avatar: 'https://picsum.photos/id/1016/100/100',
    status: 'Contacted',
    campaign: 'Summer Sale 2024',
    source: 'Website Form',
    lastContacted: '2024-07-30',
    history: [
        { date: '2024-07-30', action: 'Emailed', details: 'Sent follow-up email.' },
        { date: '2024-07-28', action: 'Emailed', details: 'Sent introductory email.' },
    ],
  },
];

export const campaigns: Campaign[] = [
  {
    id: '1',
    name: 'Summer Sale 2024',
    status: 'Active',
    startDate: '2024-06-01',
    endDate: '2024-08-31',
    leads: 120,
    responseRate: 65,
  },
  {
    id: '2',
    name: 'Q3 Webinar Series',
    status: 'Active',
    startDate: '2024-07-15',
    endDate: '2024-09-15',
    leads: 85,
    responseRate: 45,
  },
  {
    id: '3',
    name: 'New Feature Launch',
    status: 'Completed',
    startDate: '2024-05-10',
    endDate: '2024-06-10',
    leads: 250,
    responseRate: 80,
  },
  {
    id: '4',
    name: 'Holiday Promotion',
    status: 'Paused',
    startDate: '2024-11-01',
    endDate: '2024-12-25',
    leads: 50,
    responseRate: 20,
  },
  {
    id: '5',
    name: 'Q4 Product Showcase',
    status: 'Draft',
    startDate: '2024-10-01',
    endDate: '2024-10-31',
    leads: 0,
    responseRate: 0,
  },
];
